// lib/validation.ts
import { z } from "zod";
import { ORDER_STATUS, EMAIL_TYPE } from "./constants";

export const OrderStatusSchema = z.enum([
  ORDER_STATUS.PENDING,
  ORDER_STATUS.PAID,
  ORDER_STATUS.IN_PROGRESS,
  ORDER_STATUS.DONE,
  ORDER_STATUS.REFUNDED,
]);

export const EmailTypeSchema = z.enum([
  EMAIL_TYPE.PAYMENT_RECEIVED,
  EMAIL_TYPE.UPLOAD_REQUEST_INITIAL,
  EMAIL_TYPE.UPLOAD_REMINDER_1,
  EMAIL_TYPE.UPLOAD_REMINDER_2,
  EMAIL_TYPE.DOCUMENTS_RECEIVED,
  EMAIL_TYPE.WORK_STARTED,
  EMAIL_TYPE.COMPLETION,
  EMAIL_TYPE.REFUND_APPROVED,
]);